### ISSUE TITLE
Improvements on the landing page

### ISSUE THREAD

**Issue by TLiebich** [bigdoods/ifc-tech.org#38]
**This is a...**

- [ ] Feature Request
- [ ] Bug Report
- [x] Improvement Report

**Problem:**
correct and improve content on the main landing page

**Proposed Solution:**
instead "Since 2001, IFC is a data model structure that makes it possible to hold and exchange relevant data between different software applications"

write "IFC, short for "Industry Foundation Classes", are a data schema enabling the exchange and sharing of relevant data between different software applications in the construction and operation of built facilities. Having the roots back to 1996, the IFC have been continuosly enhanced to support software interoperability for openBIM."

instead "openbim
Digital building data represented in the EXPRESS data modelling language enable the application of an expanding set of building elements for a building."

write "openBIM
Digital construction and operation data representations provided in either the EXPRESS or XML Schema data modeling language to built interfaces to share different model elements for built assets."

instead "BuildingSmart mark of approval
This specification, ISO 16739, developed and updated by Buildingsmart International gives your customers assurance when using your software in their workflows"

write "buildingSMART mark of approval
This specification, ISO 16739, developed and updated by buildingSMART International, and fomally standardized by the International Standard Organization, ISO, gives your customers assurance when using your software in their workflows"

**Page to Update:**
http://ifc-tech.org

**Comment by bigdoods** [comment]
@TLiebich I have made updates as described above.
