### ISSUE TITLE
add a menu (sub structure) for sharing sample ifc files

### ISSUE THREAD

**Issue by TLiebich** [bigdoods/ifc-tech.org#40]
**This is a...**

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Many develope search for small unit test files as a starting point. We need a section on the ifc-tech side to enable sharing of sample files

**Proposed Solution:**
Add such a section, and add a disclaimer, saying that those files are shared by the community and may not comply with all rules.

**Page to Update:**
http://ifc-tech.org/...

**Comment by bigdoods** [comment]
Agreed. Added this section to the tools page.
