### ISSUE TITLE
What is the general aim of this repository?

### ISSUE THREAD

**Issue by klacol** [bigdoods/ifc-tech.org#60]
**This is a...**

- [ ] Feature Request
- [ ] Bug Report
- [x] Question

First of all: Congrats to this approach!

Please explain the general plan with this repository and the page https://www.ifc-tech.org.

Is this a testing environment or will it stay on the long run?
Which elements from http://www.buildingsmart-tech.org shall be migrated to https://www.ifc-tech.org?
How is this repo related to the official repo at https://github.com/buildingsmart?

Thanks!

**Comment by bigdoods** [comment]
Hi Klaus,

Thank you for your message and sorry about the delay in getting back to you.

BuildingSMART commissioned the development of this as a pilot project for a centralised community knowledgebase for Open technologies in the organisation. 

The idea was that we would migrate all of the content from buildingsmart-tech website to this site and appoint a buildingsmart member as an administrator that would act as a gatekeeper for the content submitted by the community. This way, incremental improvements could be made and everybody could contribute as long as they had a github account.

After three months of development, the project has stopped and the site serves no purpose anymore other than an example for the next version to use as a base ( conceptually ). 

This repo remains a great project base to continue building on but it will be classed as an "unofficial" solution to the demand for a centralised community knowledgebase unless buildingSMART renew their interest.

Hopefully there will be some progress soon!

**Comment by klacol** [comment]
Hi John, thanks for the clarification.
